### ISSUE TITLE
Support Docker image

### ISSUE THREAD

**Issue by Jengro777** [elliotchance/vsql#210]
Please provide a file called `docker-compose.yml`

 During deployment, only `docker-compose up-d`  is needed

**Comment by elliotchance** [comment]
There are already prebuilt images available: https://vsql.readthedocs.io/en/latest/docker.html and there is a Dockerfile there to generate dev builds, if you need to.

docker composer is only useful for external applications that use vsql as a dependency.

**Comment by Jengro777** [comment]
docker-compose.yml
```
services:
  vsql-server:
    image: elliotchance/vsql:latest
    container_name: vsql-server
    volumes:
      - ./data/db:/db
    command: ["server", "/db/mydb.vsql"]
    stdin_open: true
    tty: true
    ports:
      - "3210:9000"
```

![Image](https://github.com/user-attachments/assets/1645683a-06cd-4e04-a791-c7bb1b2f52a1)
@elliotchance
